/*
 * If you need to initialize your database with some data, you may write a script
 * to do so here.
 */
'use strict';
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function seedData() {
    const mockData = {
        "users": [{
            utorid: "regular1",
            name: "Reg 001",
            email: "reg001@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "regular",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "regular2",
            name: "Reg 002",
            email: "reg002@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "regular",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "regular3",
            name: "Reg 003",
            email: "reg003@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "regular",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "regular4",
            name: "Reg 004",
            email: "reg004@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "regular",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "manager1",
            name: "Man 001",
            email: "man001@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "manager",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "manager2",
            name: "Man 002",
            email: "man002@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "manager",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "manager3",
            name: "Man 003",
            email: "man003@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "manager",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "manager4",
            name: "Man 004",
            email: "man004@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "manager",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "super001",
            name: "Sup 001",
            email: "sup001@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "superuser",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "super002",
            name: "Sup 002",
            email: "sup002@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "superuser",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }, {
            utorid: "super003",
            name: "Sup 003",
            email: "sup003@mail.utoronto.ca",
            password: "Password1!",
            birthday: new Date("2000-01-01"),
            role: "superuser",
            points: 0,
            avatarUrl: "",
            suspicious: false,
            verified: true,
            createdAt: "2025-02-22T00:00:00.000Z",
            expiresAt: "2025-11-22T00:00:00.000Z",
            lastLogin: "2025-02-24T00:00:00.000Z"
        }],
        "events": [
        {
            name: "Event 1",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 2",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 3",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 4",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 5",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 6",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 7",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 8",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 9",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 10",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 12",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }, {
            name: "Event 11",
            description: "dummy event",
            location: "toronto",
            startTime: "2025-12-02T00:00:00.000Z",
            endTime: "2025-12-22T00:00:00.000Z",
            capacity: 67,
            pointsRemain: 100,
            pointsAwarded: 0,
            published: true
        }],
        "transactions": [{
            "utorid":"clive123",
            "type":"redemption",
            "spent":80,
            "earned":43,
            "remark":"test",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":44,
            "sender":"clive123",
            "recipient":"123",
            "awarded":4,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"event",
            "spent":null,
            "earned":null,
            "remark":null,
            "createdBy":"user003",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":"alice123",
            "awarded":10,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"john",
            "type":"event",
            "spent":null,
            "earned":null,
            "remark":null,
            "createdBy":"user003",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":"john",
            "awarded":10,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"event",
            "spent":null,
            "earned":null,
            "remark":null,
            "createdBy":"user003",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":"clive123",
            "awarded":10,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"purchase",
            "spent":30,
            "earned":120,
            "remark":"test remark",
            "createdBy":"user003",
            "suspicious":false,
            "amount":120,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":"Hi robert, I'm transferring 50 points to you!",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-50,
            "sender":"alice123",
            "recipient":"robert1",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"robert1",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":"Hi robert, I'm transferring 50 points to you!",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":50,
            "sender":"alice123",
            "recipient":"robert1",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"redemption",
            "spent":0,
            "earned":0,
            "remark":"redeeming 20 points for alice123",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-20,
            "sender":null,
            "recipient":null,
            "awarded":0,
            "processedBy":"clive123",
            "processed":true
        }, {
            "utorid":"clive123",
            "type":"redemption",
            "spent":0,
            "earned":0,
            "remark":"redeem 30 points for clive123!",
            "createdBy":"clive123",
            "suspicious":false,
            "amount":-30,
            "sender":null,
            "recipient":null,
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"purchase",
            "spent":50,
            "earned":200,
            "remark":"",
            "createdBy":"user003",
            "suspicious":false,
            "amount":200,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"adjustment",
            "spent":0,
            "earned":0,
            "remark":"",
            "createdBy":"user003",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"adjustment",
            "spent":0,
            "earned":0,
            "remark":"",
            "createdBy":"user003",
            "suspicious":false,
            "amount":-5,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"purchase",
            "spent":15,
            "earned":60,
            "remark":"",
            "createdBy":"user003",
            "suspicious":false,
            "amount":60,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-50,
            "sender":"alice123",
            "recipient":"john",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"john",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":50,
            "sender":"alice123",
            "recipient":"john",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"redemption",
            "spent":0,
            "earned":0,
            "remark":"redeeming points for alice123",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-50,
            "sender":null,
            "recipient":null,
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":"sending points to user123",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-20,
            "sender":"alice123",
            "recipient":"user123",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"user123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":"sending points to user123",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":20,
            "sender":"alice123",
            "recipient":"user123",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"adjustment",
            "spent":0,
            "earned":0,
            "remark":"",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"john",
            "type":"adjustment",
            "spent":0,
            "earned":0,
            "remark":"",
            "createdBy":"alice123",
            "suspicious":false,
            "amount":10,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-10,
            "sender":"alice123",
            "recipient":"clive123",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":10,
            "sender":"alice123",
            "recipient":"clive123",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-10,
            "sender":"alice123",
            "recipient":"robert1",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"robert1",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":10,
            "sender":"alice123",
            "recipient":"robert1",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"alice123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":-10,
            "sender":"alice123",
            "recipient":"user001",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"user001",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"alice123",
            "suspicious":false,
            "amount":10,
            "sender":"alice123",
            "recipient":"user001",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"clive123",
            "suspicious":false,
            "amount":-10,
            "sender":"clive123",
            "recipient":"user003",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"user003",
            "type":"transfer",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"clive123",
            "suspicious":false,
            "amount":10,
            "sender":"clive123",
            "recipient":"user003",
            "awarded":0,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"user005",
            "type":"purchase",
            "spent":20,
            "earned":80,
            "remark":"",
            "createdBy":"clive123",
            "suspicious":false,
            "amount":80,
            "sender":null,
            "recipient":null,
            "awarded":null,
            "processedBy":null,
            "processed":false
        }, {
            "utorid":"clive123",
            "type":"redemption",
            "spent":0,
            "earned":0,
            "remark":null,
            "createdBy":"clive123",
            "suspicious":false,
            "amount":-10,
            "sender":null,
            "recipient":null,
            "awarded":0,
            "processedBy":null,
            "processed":false
            }],
        "promotions": [{
            "id":1,
            "name":"Testing Promo",
            "type":"Transaction",
            "startTime":"2025-12-04 21:45:09",
            "endTime":"2025-12-04 16:45:58",
            "isOneTime":true,
            "minSpending":45,
            "rate":4,
            "points":3,
            "description":"test"
        },{
            "id":2,
            "name":"promo2",
            "type":"Transaction",
            "startTime":"2025-12-09 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":true,
            "minSpending":30,
            "rate":4,
            "points":10,
            "description":"test"
        },{
            "id":3,
            "name":"promo3",
            "type":"Transaction",
            "startTime":"2025-12-22 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":false,
            "minSpending":50,
            "rate":3,
            "points":5,
            "description":"test"
        },{
            "id":4,
            "name":"promo4",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-25 00:00:00",
            "isOneTime":false,
            "minSpending":10,
            "rate":3,
            "points":5,
            "description":"test"
        },{
            "id":5,
            "name":"promo5",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-25 00:00:00",
            "isOneTime":true,
            "minSpending":10,
            "rate":4,
            "points":5,
            "description":"test"
        },{
            "id":6,
            "name":"promo6",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":true,
            "minSpending":10,
            "rate":4,
            "points":10,
            "description":"test"
        },{
            "id":7,
            "name":"promo7",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":false,
            "minSpending":10,
            "rate":5,
            "points":10,
            "description":"test"
        },{
            "id":8,
            "name":"promo8",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":true,
            "minSpending":20,
            "rate":3,
            "points":20,
            "description":null
        },{
            "id":9,
            "name":"promo9",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":false,
            "minSpending":20,
            "rate":2,
            "points":10,
            "description":null
        },{
            "id":10,
            "name":"promo10",
            "type":"Transaction",
            "startTime":"2025-12-01 00:00:00",
            "endTime":"2025-12-31 00:00:00",
            "isOneTime":true,
            "minSpending":10,
            "rate":3,
            "points":10,
            "description":null
        }]
    };

    for (const user of mockData.users) {
        await prisma.user.create({ data: user });
    }

    for (const event of mockData.events) {
        await prisma.event.create({ data: event });
    }

    for (const transaction of mockData.transactions) {
        await prisma.transaction.create({ data: transaction });
    }

    for (const promo of mockData.promotions) {
        await prisma.promotion.create({ data: promo });
    }
}

seedData().finally(() => prisma.$disconnect());
